Repository Decentra-Network/Messaging_App, pull requests merged in 2021-04, with the labels that each got.

#2 A new gui
  web/static/HELP-US-OUT.txt
  web/static/css/font-awesome.css
  web/static/css/font-awesome.min.css
  web/static/css/main.css
  web/static/fonts/FontAwesome.otf
  web/static/fonts/fontawesome-webfont.eot
  web/static/fonts/fontawesome-webfont.svg
  web/static/fonts/fontawesome-webfont.ttf
  web/static/fonts/fontawesome-webfont.woff
  web/static/fonts/fontawesome-webfont.woff2
  web/static/less/animated.less
  web/static/less/bordered-pulled.less
  web/static/less/core.less
  web/static/less/fixed-width.less
  web/static/less/font-awesome.less
  web/static/less/icons.less
  web/static/less/larger.less
  web/static/less/list.less
  web/static/less/mixins.less
  web/static/less/path.less
  web/static/less/rotated-flipped.less
  web/static/less/screen-reader.less
  web/static/less/stacked.less
  web/static/less/variables.less
  web/static/scss/_animated.scss
  web/static/scss/_bordered-pulled.scss
  web/static/scss/_core.scss
  web/static/scss/_fixed-width.scss
  web/static/scss/_icons.scss
  web/static/scss/_larger.scss
  web/static/scss/_list.scss
  web/static/scss/_mixins.scss
  web/static/scss/_path.scss
  web/static/scss/_rotated-flipped.scss
  web/static/scss/_screen-reader.scss
  web/static/scss/_stacked.scss
  web/static/scss/_variables.scss
  web/static/scss/font-awesome.scss
  web/templates/base.html
  web/templates/home.html
  web/templates/messages-col.html
  web/templates/messages.html
  web/templates/user-list.html
Labels: enhancement

#3 removed unused a local variable
  func/send.py
Labels: bug

#4 Some Fixing for New App Structure
  .gitignore
  messaging_app_main.py
  test/test_message.py
  test/test_rsa.py
  test/test_user.py
  web/chat.py
Labels: Fixing, enhancement
